### PR TITLE
Upgrade dependencies

### LINKED ISSUE #4: package lock dependencies
PeerDependencies warnings:
https://github.com/martinmcwhorter/commitiquette/blob/2fae504b621266974a764aabb82f9c95474966a0/package.json#L55
don't match:
https://github.com/martinmcwhorter/commitiquette/blob/2fae504b621266974a764aabb82f9c95474966a0/package.json#L21

@commitlint/cli must be v9.1.2 instead of v9.1.1
commitizen must be v4.1.2 instad of v4.0.3
there is also eslint v7.7.0

### PR DESCRIPTION
**Pull request by xeptore**
Upgrade all dependencies to their latest version.

Closes #4.

### CODE REVIEW

**Comment by martinmcwhorter** [comment]
It looks like tests failed in relation to full-stop. 

I think commitlint used to require a provided full-stop char, but then they removed that param. If I remember right.

**Comment by xeptore** [comment]
About the failing tests, there is a bug I found in some rule configuration type declarations of [`@commitlint/types` package](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/types). I made a PR yesterday that fixes this bug here: conventional-changelog/commitlint#2534, and at the time of writing this, it seems it will be accepted and possibly merged soon.

**Comment by xeptore** [comment]
conventional-changelog/commitlint#2534 has been merged. Waiting for the new version publish to update our dependencies.

**Comment by martinmcwhorter** [comment]
@xeptore I believe the changes you made to commitlint have been released. Can you update this PR with an updated commitlint version?

**Comment by xeptore** [comment]
@martinmcwhorter, all outdated dependencies, including commitlint were updated. It seems it is a bad credential error that causes the _Node.js CI_ job to fail, and everything else is working fine.

**Review by martinmcwhorter — APPROVED** [review]

**Pull request merged**
